language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
before_install:
  - pip install poetry
install:
  - pip install tox-travis
script:
  - tox
env:
  global:
    - secure: soSoK7/zkhsCvZedS3k/79HBfH2JRFSJopxs4S/gSMSIJs7lWDvYJg6NDyXudi8OvC3ytVdOxRoK38PlTsuRMOUDB5L/MlzK3rrt/qpb6hKlbnfw2Sd68BG7E0qagfkSGpRlxm6YnZGhg5qmgSNJhq9QOQ35vlCblM7hsdCOvj8teMqVZ1k/ACNl9rC7twQMSoParUp40xLKa2RcWcoo01WL7ipvye/Q5bjYABtFcLz8Dg115co9UuTNKx2lzVO3FQD+2dgR3bqz4cFEN/SjuctDcnlCuUttGWi61Kph0fTl6wYWMerD6cenwH2Zl54SQizpxzDwOr/9BeV79spFAfXXHN6bjOkWnvyz2fiDcoNulH4Kv7+HldKab7alkj4uAzlIwiJlLqXzorSUsPa8E7+GtIy5GabAqxrMlzBNnF+SfkoySGwvHW9wXF53cBiVWVj4KBsGLiltWgIbGnWScG/Kftx3n3+xzZUw6ZVTpEGPaCqqLNA8UFVpt1+BMB/2rNWRgRJVjzsgooRnc8O5Cek+tOGpqQAFoyfTenTESyORBQaYzNnNaSXg1/yKs6t8OVwkvLC6BXOX5EtLBd1WPrDZD617Iqxs01NjmXS6HAP89klRp8TJDJTyq2d/DAgzDM1f3PBYcd2SEtWDJXxBJF10ZEg+xyLpraoWyDR8Ll0=

notifications:
  webhooks: https://outlook.office.com/webhook/1cdb97d0-f7af-400c-a9c9-df03f0f8ffe7@cebf6378-033a-423b-b2fd-55940925abf6/TravisCI/1ae4691f82e048f88c7f8642944d2c3b/35799091-25ec-465e-a063-04f4614d2e7e
